### ISSUE TITLE
Install autonotify_observe

### ISSUE THREAD

**Issue by joo** [dam0vm3nt/polymer_autonotify#9]
pubspec.yaml: 

name: test_polymer
version: 0.0.1
description: A sample command-line application.
author: <Joo Tsao> joo.tsao@gmail.com
dependencies:
  polymer: ^1.0.0-rc.15
  web_components: ^0.12.0
  browser: ^0.10.0
  autonotify_observe: ^1.0.0+7
transformers:
- autonotify_observe
- polymer:
  entry_points:
  - web/index.html

run pub get show error:

Working dir: /home/joo/doc/work/intellij/test
/home/joo/opt/dart-sdk/bin/pub get
Resolving dependencies...
Git error. Command: git fetch
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Process finished with exit code 1

**Comment by dam0vm3nt** [comment]
sorry, but running `pub get` on freshly create project using your `pubspec.yaml` is working for me.

This is the resulting `pubspec.lock` : 

``` yaml
packages:
  analyzer:
    description: analyzer
    source: hosted
    version: "0.27.1"
  args:
    description: args
    source: hosted
    version: "0.13.3+1"
  async:
    description: async
    source: hosted
    version: "1.7.0"
  autonotify_observe:
    description: autonotify_observe
    source: hosted
    version: "1.0.0+7"
  barback:
    description: barback
    source: hosted
    version: "0.15.2+7"
  browser:
    description: browser
    source: hosted
    version: "0.10.0+2"
  charcode:
    description: charcode
    source: hosted
    version: "1.1.0"
  cli_util:
    description: cli_util
    source: hosted
    version: "0.0.1+2"
  code_transformers:
    description: code_transformers
    source: hosted
    version: "0.3.1"
  collection:
    description: collection
    source: hosted
    version: "1.2.0"
  crypto:
    description: crypto
    source: hosted
    version: "0.9.1"
  csslib:
    description: csslib
    source: hosted
    version: "0.12.2"
  dart_style:
    description: dart_style
    source: hosted
    version: "0.2.4"
  glob:
    description: glob
    source: hosted
    version: "1.1.0"
  html:
    description: html
    source: hosted
    version: "0.12.2+1"
  http_multi_server:
    description: http_multi_server
    source: hosted
    version: "2.0.0"
  http_parser:
    description: http_parser
    source: hosted
    version: "2.0.0"
  initialize:
    description: initialize
    source: hosted
    version: "0.6.2+1"
  logging:
    description: logging
    source: hosted
    version: "0.11.2"
  matcher:
    description: matcher
    source: hosted
    version: "0.12.0+1"
  mime:
    description: mime
    source: hosted
    version: "0.9.3"
  observe:
    description:
      ref: reflectable
      resolved-ref: add4c1ba6339163b80cbbde3dc3a1918adb352bc
      url: "https://github.com/dam0vm3nt/observe.git"
    source: git
    version: "0.13.1+2"
  package_config:
    description: package_config
    source: hosted
    version: "0.1.3"
  path:
    description: path
    source: hosted
    version: "1.3.9"
  plugin:
    description: plugin
    source: hosted
    version: "0.1.0"
  polymer:
    description: polymer
    source: hosted
    version: "1.0.0-rc.15"
  polymer_autonotify:
    description: polymer_autonotify
    source: hosted
    version: "1.0.0"
  polymer_interop:
    description: polymer_interop
    source: hosted
    version: "1.0.0-rc.8"
  pool:
    description: pool
    source: hosted
    version: "1.2.1"
  pub_semver:
    description: pub_semver
    source: hosted
    version: "1.2.3"
  reflectable:
    description: reflectable
    source: hosted
    version: "0.5.1"
  shelf:
    description: shelf
    source: hosted
    version: "0.6.4+3"
  shelf_static:
    description: shelf_static
    source: hosted
    version: "0.2.3+2"
  shelf_web_socket:
    description: shelf_web_socket
    source: hosted
    version: "0.0.1+5"
  source_map_stack_trace:
    description: source_map_stack_trace
    source: hosted
    version: "1.0.4"
  source_maps:
    description: source_maps
    source: hosted
    version: "0.10.1"
  source_span:
    description: source_span
    source: hosted
    version: "1.2.1"
  stack_trace:
    description: stack_trace
    source: hosted
    version: "1.6.0"
  string_scanner:
    description: string_scanner
    source: hosted
    version: "0.1.4+1"
  test:
    description: test
    source: hosted
    version: "0.12.7"
  utf:
    description: utf
    source: hosted
    version: "0.9.0+2"
  watcher:
    description: watcher
    source: hosted
    version: "0.9.7"
  web_components:
    description: web_components
    source: hosted
    version: "0.12.2+2"
  when:
    description: when
    source: hosted
    version: "0.2.0"
  which:
    description: which
    source: hosted
    version: "0.1.3"
  yaml:
    description: yaml
    source: hosted
    version: "2.1.8"

```

Please note that one dependency is a git dep. Are you able to do a `git clone` of that repo in your environment ?
